//
// Define macro for the compiler for either options or functions
//

#ifndef _MISC_COMPILEROPTIONS_H_
#define _MISC_COMPILEROPTIONS_H_

#define RESIZABLEARRAY_ADDVALUEINTERFACE
#undef RESIZABLEARRAY_ADDVALUEINTERFACE
#define RESIZABLEARRAY_SLOWADD
#undef RESIZABLEARRAY_SLOWADD

#define RESIZABLEARRAY_STLIMPL
#undef RESIZABLEARRAY_STLIMPL

#ifdef _DEBUG
#define RESIZABLEARRAY_CHECKBOUNDS
#endif

#define STRING_CHUNKSIZE 256

#endif
