// this file is here to ensure compilation of the various vmath stuff
// since all the code is in .h files, this is probably the best method to
// do a mega include

#include "consts.h"
#include "frame.h"
#include "frustum.h"
#include "functions.h"
#include "vfunctions.h"
#include "interval.h"
#include "matrix2.h"
#include "matrix3.h"
#include "matrix4.h"
#include "plane.h"
#include "projection.h"
#include "range1.h"
#include "range2.h"
#include "range3.h"
#include "spline.h"
#include "uspline.h"
#include "vec2.h"
#include "vec3.h"
#include "vec4.h"
#include "tuple2.h"
#include "tuple3.h"
#include "geom3.h"
#include "spectrum3.h"
#include "geomrange3.h"
#include "linearmap3.h"
#include "streamMethods.h"
